Feature: componente lista horta
Apple-Developer-Residence-IFCE/HortCult-PotatosHead pull request #2
Opened 2023-05-25 23:12 UTC by joaocanuto

2023-05-26 00:31 UTC, carlosamorim28 requested changes

2023-05-26 00:31 UTC, carlosamorim28 commented on HortCult-PotatosHead/Views/MinhaHorta/HeaderMenu.swift
> +            .padding(.top, 10)
talvez retirar a margem de cima e da lateral para deixar elas para serem colocadas na implementação da tela

2023-05-26 22:02 UTC, joaocanuto commented on HortCult-PotatosHead/Views/MinhaHorta/HeaderMenu.swift
> +            .padding(.top, 10)
Feito.

2023-05-27 00:39 UTC, carlosamorim28 approved these changes

2023-05-29 21:13 UTC, merged